### ISSUE TITLE
octodns-dnsmadeeasy provider has not had a new  release

### ISSUE THREAD

**Issue by npaufler** [octodns/octodns-dnsmadeeasy#15]
The version of the octodns-dnsmadeeasy provider (installable from both pip and dockerhub) is still 
From this commit: https://github.com/octodns/octodns-dnsmadeeasy/commit/1a71b25259d80a64138d8663636c11081ec1ff88
from July 2022.

Is it possible to get a new release shipped for this (and preferably pushed to Dockerhub) so that the root NS support change can be used? Let me know if there's anything I can contribute to facilitate that. Thanks!

cc: @ross

**Comment by ross** [comment]
Looks like the notable changes in in that time are root ns support and a user agent on the api requests, https://github.com/octodns/octodns-dnsmadeeasy/compare/1a71b25...main. 

Will queue it up on the todo list.

**Comment by npaufler** [comment]
Thanks! Much appreciated.

**Comment by ross** [comment]
Fixed by https://github.com/octodns/octodns-dnsmadeeasy/pull/16

**Comment by npaufler** [comment]
Thanks @ross -- appreciate the quick turnaround.

What's the process for getting this into the Docker images -- is this a matter of waiting on the new monthly image tag next month?

**Comment by npaufler** [comment]
Nice! That's super convenient. Once again, appreciate you and your teams effort on this. Really pleased with octodns so far.
